# Generated by Django 6.0.4 on 2026-04-21 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usimamizi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kitengo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jina", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Mshiriki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namba_ya_kifua", models.CharField(max_length=10, unique=True)),
                (
                    "kitengo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mashindano.kitengo",
                    ),
                ),
                (
                    "mwanafunzi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usimamizi.mwanafunzi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saka_kubwa", models.IntegerField(default=0, help_text="Makato -5")),
                ("saka_dogo", models.IntegerField(default=0, help_text="Makato -3")),
                ("kibw", models.IntegerField(default=0, help_text="Makato -4")),
                ("neno", models.IntegerField(default=0, help_text="Makato -2")),
                ("shakli", models.IntegerField(default=0, help_text="Makato -1")),
                (
                    "makosa_tajweed",
                    models.IntegerField(default=0, help_text="Kila kosa -2"),
                ),
                (
                    "makosa_makharij",
                    models.IntegerField(default=0, help_text="Kila kosa -2"),
                ),
                ("alama_hifdh", models.IntegerField(default=50, editable=False)),
                ("alama_tajweed", models.IntegerField(default=30, editable=False)),
                ("alama_makharij", models.IntegerField(default=20, editable=False)),
                ("jumla_kuu", models.IntegerField(default=100, editable=False)),
                (
                    "jaji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usimamizi.mwalimu",
                    ),
                ),
                (
                    "mshiriki",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mashindano.mshiriki",
                    ),
                ),
            ],
        ),
    ]
