# Generated by Django 5.1.3 on 2026-04-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mashindano", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alama",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="kitengo",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mshiriki",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
