# Generated by Django 4.2.30 on 2026-07-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashindano', '0002_alter_alama_id_alter_kitengo_id_alter_mshiriki_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alama',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kitengo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mshiriki',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
