# Generated by Django 6.0.4 on 2026-04-21 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Darasa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jina",
                    models.CharField(
                        help_text="Mfano: Darasa la Kwanza, Ibtidai, n.k.",
                        max_length=50,
                    ),
                ),
                ("maelezo", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mtihani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jina_la_mtihani", models.CharField(max_length=100)),
                ("tarehe", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Tangazo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kichwa_cha_habari", models.CharField(max_length=200)),
                ("maelezo", models.TextField()),
                ("tarehe_iliyotolewa", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mwalimu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "namba_ya_simu",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "cheo",
                    models.CharField(
                        choices=[
                            ("Mwalimu Mkuu", "Mwalimu Mkuu"),
                            ("Mwalimu wa Kawaida", "Mwalimu wa Kawaida"),
                            ("Jaji", "Jaji"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "picha",
                    models.ImageField(
                        blank=True, null=True, upload_to="picha_za_walimu/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mwanafunzi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jina_kamili", models.CharField(max_length=100)),
                ("namba_ya_usajili", models.CharField(max_length=20, unique=True)),
                ("umri", models.IntegerField(blank=True, null=True)),
                (
                    "mahala_anapoishi",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "jina_la_mzazi",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "namba_ya_simu_mzazi",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "jinsia",
                    models.CharField(
                        choices=[("ME", "Mwanamume (ME)"), ("KE", "Mwanamke (KE)")],
                        default="ME",
                        max_length=2,
                    ),
                ),
                ("juzuu_aliyohifadhi", models.IntegerField(default=1)),
                ("tarehe_ya_kujiunga", models.DateField(auto_now_add=True)),
                (
                    "darasa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usimamizi.darasa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matokeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maksi", models.FloatField()),
                (
                    "mtihani",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usimamizi.mtihani",
                    ),
                ),
                (
                    "mwanafunzi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usimamizi.mwanafunzi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hudhurio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarehe", models.DateField(auto_now_add=True)),
                ("yupo", models.BooleanField(default=True)),
                ("sababu_kama_hayupo", models.TextField(blank=True, null=True)),
                (
                    "aina_ya_rekodi",
                    models.CharField(
                        choices=[
                            ("Kawaida", "Madrasa ya Kawaida"),
                            ("Hifdhu", "Somo la Hifdhu"),
                        ],
                        default="Kawaida",
                        max_length=20,
                    ),
                ),
                (
                    "mwanafunzi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usimamizi.mwanafunzi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RekodiHifdhu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarehe", models.DateField(auto_now_add=True)),
                (
                    "sabaq_sura",
                    models.CharField(
                        blank=True,
                        help_text="Mfano: Al-Baqarah",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("sabaq_aya_kuanzia", models.IntegerField(blank=True, null=True)),
                ("sabaq_aya_kuishia", models.IntegerField(blank=True, null=True)),
                (
                    "sabaq_hali",
                    models.CharField(
                        blank=True,
                        choices=[("Kajua", "✅ Kajua"), ("Hajajua", "❌ Hajajua")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "sabaq_ya_kesho",
                    models.CharField(
                        blank=True,
                        help_text="Mfano: Aya 16-20 (Kama amepasi)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("maoni_ya_mwalimu", models.TextField(blank=True, null=True)),
                (
                    "mwalimu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usimamizi.mwalimu",
                    ),
                ),
                (
                    "mwanafunzi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usimamizi.mwanafunzi",
                    ),
                ),
            ],
            options={
                "ordering": ["-tarehe"],
            },
        ),
        migrations.CreateModel(
            name="PandeMurajaa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sura", models.CharField(max_length=50)),
                ("aya_kuanzia", models.IntegerField(blank=True, null=True)),
                ("aya_kuishia", models.IntegerField(blank=True, null=True)),
                (
                    "hali",
                    models.CharField(
                        choices=[
                            ("Pasi", "✅ Pasi"),
                            ("Makosa", "⚠️ Makosa Madogo"),
                            ("Feli", "❌ Feli"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rekodi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapande",
                        to="usimamizi.rekodihifdhu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Somo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jina",
                    models.CharField(
                        help_text="Mfano: Fiqhi, Tawheed, Hifdhu (Tashjii)",
                        max_length=100,
                    ),
                ),
                (
                    "ni_la_hifdhu",
                    models.BooleanField(
                        default=False,
                        help_text="Weka TIKI hapa kama hili ni somo maalum la Hifdhu linalohitaji Mahudhurio na Sabaq zake",
                    ),
                ),
                (
                    "mwalimu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usimamizi.mwalimu",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rekodihifdhu",
            name="somo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usimamizi.somo"
            ),
        ),
        migrations.CreateModel(
            name="Nyenzo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jina_la_faili", models.CharField(max_length=200)),
                ("faili", models.FileField(upload_to="nyenzo_masomo/")),
                ("tarehe_iliyowekwa", models.DateTimeField(auto_now_add=True)),
                (
                    "somo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usimamizi.somo"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mwanafunzi",
            name="programu_ya_usiku",
            field=models.ForeignKey(
                blank=True,
                help_text="Chagua kama anasoma usiku (Acha wazi kama hasomi usiku)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wanafunzi_usiku",
                to="usimamizi.somo",
            ),
        ),
        migrations.AddField(
            model_name="mtihani",
            name="somo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usimamizi.somo"
            ),
        ),
    ]
