# Generated by Django 6.0.4 on 2026-04-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usimamizi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rekodihifdhu",
            name="sabaq_ya_kesho",
        ),
        migrations.AlterField(
            model_name="rekodihifdhu",
            name="sabaq_hali",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kajua", "✅ Kajua"),
                    ("Hajajua", "❌ Hajajua"),
                    ("Hajasikilizwa", "⏸️ Hajasikilizwa"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rekodihifdhu",
            name="sabaq_sura",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
