# Generated by Django 6.0.4 on 2026-04-22 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usimamizi", "0002_remove_rekodihifdhu_sabaq_ya_kesho_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RekodiMaendeleoMchana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarehe", models.DateField(auto_now_add=True)),
                (
                    "mada_iliyosomwa",
                    models.CharField(help_text="Mfano: Mlango wa Udhu", max_length=200),
                ),
                (
                    "ukurasa_au_aya",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "hali",
                    models.CharField(
                        choices=[
                            ("Ameelewa", "✅ Ameelewa"),
                            ("Hajaelewa", "❌ Hajaelewa"),
                            ("Hajasikilizwa", "⏸️ Hajasikilizwa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("maoni", models.TextField(blank=True, null=True)),
                (
                    "mwalimu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usimamizi.mwalimu",
                    ),
                ),
                (
                    "mwanafunzi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usimamizi.mwanafunzi",
                    ),
                ),
                (
                    "somo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usimamizi.somo"
                    ),
                ),
            ],
        ),
    ]
