# Generated by Django 6.0.4 on 2026-04-22 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usimamizi", "0003_rekodimaendeleomchana"),
    ]

    operations = [
        migrations.AddField(
            model_name="rekodihifdhu",
            name="aina_ya_rekodi",
            field=models.CharField(
                choices=[("Darasa", "Darasa"), ("Usiku", "Usiku")],
                default="Usiku",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rekodihifdhu",
            name="darasa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usimamizi.darasa",
            ),
        ),
        migrations.AlterField(
            model_name="rekodihifdhu",
            name="somo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usimamizi.somo",
            ),
        ),
    ]
