# Generated by Django 6.0.4 on 2026-04-22 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usimamizi", "0004_rekodihifdhu_aina_ya_rekodi_rekodihifdhu_darasa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AinaMalipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jina",
                    models.CharField(
                        help_text="Mfano: Ada ya Mwezi Aprili, Mchango wa Mtihani",
                        max_length=100,
                    ),
                ),
                (
                    "kiasi_kinachotakiwa",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Kiasi kamili kinachopaswa kulipwa",
                        max_digits=10,
                    ),
                ),
                ("maelezo", models.TextField(blank=True, null=True)),
                ("tarehe_ya_kuanzishwa", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Malipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kiasi_kilicholipwa",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tarehe_ya_malipo", models.DateField(auto_now_add=True)),
                (
                    "njia_ya_malipo",
                    models.CharField(
                        choices=[
                            ("Cash", "Pesa Taslimu (Cash)"),
                            ("Simu", "Simu / Benki"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                ("maelezo_ya_ziada", models.TextField(blank=True, null=True)),
                (
                    "aina_ya_malipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usimamizi.ainamalipo",
                    ),
                ),
                (
                    "mpokeaji",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usimamizi.mwalimu",
                    ),
                ),
                (
                    "mwanafunzi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="malipo_yote",
                        to="usimamizi.mwanafunzi",
                    ),
                ),
            ],
            options={
                "ordering": ["-tarehe_ya_malipo"],
            },
        ),
    ]
