# Generated by Django 5.1.3 on 2026-04-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usimamizi",
            "0006_remove_mwanafunzi_umri_mwanafunzi_tarehe_ya_kuzaliwa_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mwanafunzi",
            name="jina_kamili",
            field=models.CharField(
                error_messages={"unique": "Mwanafunzi with this Jina already exists."},
                max_length=100,
                unique=True,
            ),
        ),
    ]
