# Generated by Django 5.1.3 on 2026-05-16 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usimamizi", "0007_alter_mwanafunzi_jina_kamili"),
    ]

    operations = [
        migrations.AddField(
            model_name="somo",
            name="darasa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masomo",
                to="usimamizi.darasa",
            ),
        ),
    ]
