# Generated by Django 4.2.30 on 2026-07-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usimamizi', '0008_somo_darasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsetoMtihani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(help_text='Mfano: Muhula wa 1 - 2026', max_length=100)),
                ('tarehe', models.DateField(blank=True, null=True)),
                ('maelezo', models.TextField(blank=True, null=True)),
                ('tarehe_iliyoundwa', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mseto wa Mitihani',
                'ordering': ['-tarehe_iliyoundwa'],
            },
        ),
        migrations.AlterField(
            model_name='ainamalipo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='darasa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hudhurio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='malipo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matokeo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mtihani',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mwalimu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mwanafunzi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nyenzo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pandemurajaa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rekodihifdhu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rekodimaendeleomchana',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='somo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tangazo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        # ===== HAPA NDIPO MAREKEBISHO YANAPOANZA =====
        # 1. Kwanza ongeza sehemu ya 'darasa' kwenye MsetoMtihani
        migrations.AddField(
            model_name='msetomtihani',
            name='darasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mseto_mitihani', to='usimamizi.darasa'),
        ),
        # 2. Pili, ongeza sehemu ya 'mseto' kwenye Mtihani (HII ILIKUWA IMECHELEWA)
        migrations.AddField(
            model_name='mtihani',
            name='mseto',
            field=models.ForeignKey(blank=True, help_text='Chagua mseto wa muhula ili matokeo yaingie kwenye ripoti ya jumla', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitihani', to='usimamizi.msetomtihani'),
        ),
        # 3. Mwisho kabisa, weka Constraint (sasa sehemu ya 'mseto' tayari IPO)
        migrations.AddConstraint(
            model_name='mtihani',
            constraint=models.UniqueConstraint(condition=models.Q(('mseto__isnull', False)), fields=('somo', 'mseto'), name='unique_mtihani_per_somo_mseto'),
        ),
    ]