# Generated by Django 4.2.30 on 2026-08-08 20:11

import datetime

from django.db import migrations, models
from django.db.models import Count


def dedupe_hudhurio_and_matokeo(apps, schema_editor):
    """Keep the newest row per unique key; delete older duplicates before constraints."""
    Hudhurio = apps.get_model("usimamizi", "Hudhurio")
    Matokeo = apps.get_model("usimamizi", "Matokeo")

    hudhurio_dupes = (
        Hudhurio.objects.values("mwanafunzi_id", "tarehe", "aina_ya_rekodi")
        .annotate(c=Count("id"))
        .filter(c__gt=1)
    )
    for group in hudhurio_dupes.iterator():
        ids = list(
            Hudhurio.objects.filter(
                mwanafunzi_id=group["mwanafunzi_id"],
                tarehe=group["tarehe"],
                aina_ya_rekodi=group["aina_ya_rekodi"],
            )
            .order_by("-id")
            .values_list("id", flat=True)
        )
        if len(ids) > 1:
            Hudhurio.objects.filter(id__in=ids[1:]).delete()

    matokeo_dupes = (
        Matokeo.objects.values("mtihani_id", "mwanafunzi_id")
        .annotate(c=Count("id"))
        .filter(c__gt=1)
    )
    for group in matokeo_dupes.iterator():
        ids = list(
            Matokeo.objects.filter(
                mtihani_id=group["mtihani_id"],
                mwanafunzi_id=group["mwanafunzi_id"],
            )
            .order_by("-id")
            .values_list("id", flat=True)
        )
        if len(ids) > 1:
            Matokeo.objects.filter(id__in=ids[1:]).delete()


def noop_reverse(apps, schema_editor):
    # Deduping is irreversible; constraints can still be removed by reverse migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("usimamizi", "0010_mwanafunzi_picha_nyenzo_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hudhurio",
            name="tarehe",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RunPython(dedupe_hudhurio_and_matokeo, noop_reverse),
        migrations.AddConstraint(
            model_name="hudhurio",
            constraint=models.UniqueConstraint(
                fields=("mwanafunzi", "tarehe", "aina_ya_rekodi"),
                name="unique_hudhurio_per_day_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="matokeo",
            constraint=models.UniqueConstraint(
                fields=("mtihani", "mwanafunzi"),
                name="unique_matokeo_per_mtihani_mwanafunzi",
            ),
        ),
    ]
