# Generated by Django 4.2.30 on 2026-08-08 20:48

from datetime import date

from django.db import migrations, models
import django.db.models.deletion


def seed_default_academic_period(apps, schema_editor):
    MwakaWaMasomo = apps.get_model("usimamizi", "MwakaWaMasomo")
    Muhula = apps.get_model("usimamizi", "Muhula")
    if MwakaWaMasomo.objects.exists():
        return
    year = date.today().year
    mwaka = MwakaWaMasomo.objects.create(
        jina=str(year),
        mwaka_kuanzia=year,
        mwaka_kuisha=year,
        ni_hai=True,
    )
    for namba in (1, 2):
        Muhula.objects.create(
            mwaka=mwaka,
            namba=namba,
            jina=f"Muhula wa {namba}",
            ni_hai=(namba == 1),
        )


def unseed_default_academic_period(apps, schema_editor):
    MwakaWaMasomo = apps.get_model("usimamizi", "MwakaWaMasomo")
    MwakaWaMasomo.objects.filter(jina=str(date.today().year)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("usimamizi", "0011_integrity_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Muhula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "namba",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Muhula wa 1"),
                            (2, "Muhula wa 2"),
                            (3, "Muhula wa 3"),
                        ]
                    ),
                ),
                (
                    "jina",
                    models.CharField(
                        blank=True,
                        help_text="Acha wazi ili jina lijazwe otomatiki (Muhula wa N)",
                        max_length=80,
                    ),
                ),
                ("tarehe_kuanzia", models.DateField(blank=True, null=True)),
                ("tarehe_kuisha", models.DateField(blank=True, null=True)),
                (
                    "ni_hai",
                    models.BooleanField(
                        default=False, help_text="Muhula unaotumika sasa"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Muhula",
                "ordering": ["mwaka", "namba"],
            },
        ),
        migrations.CreateModel(
            name="MwakaWaMasomo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jina",
                    models.CharField(
                        help_text="Mfano: 2025/2026", max_length=40, unique=True
                    ),
                ),
                (
                    "mwaka_kuanzia",
                    models.PositiveIntegerField(
                        help_text="Mwaka wa kuanza (mfano 2025)"
                    ),
                ),
                (
                    "mwaka_kuisha",
                    models.PositiveIntegerField(
                        help_text="Mwaka wa kuisha (mfano 2026)"
                    ),
                ),
                ("tarehe_kuanzia", models.DateField(blank=True, null=True)),
                ("tarehe_kuisha", models.DateField(blank=True, null=True)),
                (
                    "ni_hai",
                    models.BooleanField(
                        default=False,
                        help_text="Mwaka unaotumika sasa kwa ripoti na mseto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mwaka wa masomo",
                "verbose_name_plural": "Miaka ya masomo",
                "ordering": ["-mwaka_kuanzia", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="mwakawamasomo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ni_hai", True)),
                fields=("ni_hai",),
                name="unique_active_mwaka_wa_masomo",
            ),
        ),
        migrations.AddField(
            model_name="muhula",
            name="mwaka",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="muhula",
                to="usimamizi.mwakawamasomo",
            ),
        ),
        migrations.AddField(
            model_name="msetomtihani",
            name="muhula",
            field=models.ForeignKey(
                blank=True,
                help_text="Unganisha mseto na muhula wa kitaaluma kwa ripoti sahihi",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mseto_zote",
                to="usimamizi.muhula",
            ),
        ),
        migrations.AddConstraint(
            model_name="muhula",
            constraint=models.UniqueConstraint(
                fields=("mwaka", "namba"), name="unique_muhula_per_mwaka"
            ),
        ),
        migrations.AddConstraint(
            model_name="muhula",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ni_hai", True)),
                fields=("ni_hai",),
                name="unique_active_muhula",
            ),
        ),
        migrations.RunPython(
            seed_default_academic_period, unseed_default_academic_period
        ),
    ]
