# Generated by Django 4.2.30 on 2026-08-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usimamizi', '0012_academic_year_term'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RekodiMaendeleoMchana',
        ),
    ]
