# Generated by Django 4.2.30 on 2026-08-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usimamizi', '0013_remove_rekodi_maendeleo_mchana'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwanafunzi',
            name='amehifadhiwa',
            field=models.BooleanField(db_index=True, default=False, help_text='True = ameondolewa kwenye orodha hai; historia inabaki'),
        ),
        migrations.AddField(
            model_name='mwanafunzi',
            name='sababu_ya_kuhifadhiwa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mwanafunzi',
            name='tarehe_ya_kuhifadhiwa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
