# Generated by Django 4.2.30 on 2026-08-08 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usimamizi', '0014_mwanafunzi_soft_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='hudhurio',
            name='iliyorekodiwa_na',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hudhurio_zilizorekodiwa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='malipo',
            name='iliyorekodiwa_na',
            field=models.ForeignKey(blank=True, help_text='Akaunti iliyorekodi malipo (hata kama hakuna wasifu wa Mwalimu)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malipo_zilizorekodiwa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RekodiUkaguzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitendo', models.CharField(choices=[('mahudhurio_kawaida', 'Mahudhurio (kawaida)'), ('mahudhurio_hifdhu', 'Mahudhurio (hifdhu)'), ('malipo', 'Malipo')], db_index=True, max_length=40)),
                ('maelezo', models.CharField(max_length=500)),
                ('idadi_ya_rekodi', models.PositiveIntegerField(blank=True, null=True)),
                ('tarehe_ya_kitendo', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('darasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usimamizi.darasa')),
                ('malipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ukaguzi', to='usimamizi.malipo')),
                ('mtumiaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rekodi_ukaguzi', to=settings.AUTH_USER_MODEL)),
                ('mwanafunzi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usimamizi.mwanafunzi')),
                ('somo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usimamizi.somo')),
            ],
            options={
                'verbose_name': 'Rekodi ya ukaguzi',
                'verbose_name_plural': 'Rekodi za ukaguzi',
                'ordering': ['-tarehe_ya_kitendo'],
            },
        ),
    ]
