# Generated by Django 4.2.30 on 2026-08-08 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usimamizi', '0015_audit_log_mahudhurio_malipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwanafunzi',
            name='uhusiano_wa_mlezi',
            field=models.CharField(blank=True, choices=[('', '—'), ('Baba', 'Baba'), ('Mama', 'Mama'), ('Mlezi', 'Mlezi'), ('Mwingine', 'Mwingine')], default='', help_text='Uhusiano wa mzazi/mlezi anayewasiliana na ofisi', max_length=20),
        ),
        migrations.CreateModel(
            name='RekodiSimuMzazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namba_iliyopigwa', models.CharField(blank=True, default='', max_length=20)),
                ('sababu', models.CharField(choices=[('ada', 'Ada / malipo'), ('mahudhurio', 'Mahudhurio / utoro'), ('jumla', 'Habari za jumla'), ('nyingine', 'Nyingine')], db_index=True, default='ada', max_length=20)),
                ('matokeo', models.CharField(choices=[('alijibu', 'Alijibu'), ('hakujibu', 'Hakujibu'), ('imezimwa', 'Simu imezimwa'), ('siyo_sahihi', 'Namba si sahihi'), ('akaahidi', 'Akaahidi (malipo/kuja)'), ('nyingine', 'Nyingine')], db_index=True, default='alijibu', max_length=20)),
                ('maelezo', models.TextField(blank=True, default='')),
                ('tarehe_ya_simu', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('iliyorekodiwa_na', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rekodi_simu_mzazi', to=settings.AUTH_USER_MODEL)),
                ('mwanafunzi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekodi_simu', to='usimamizi.mwanafunzi')),
            ],
            options={
                'verbose_name': 'Rekodi ya simu ya mzazi',
                'verbose_name_plural': 'Rekodi za simu za wazazi',
                'ordering': ['-tarehe_ya_simu'],
            },
        ),
    ]
