# Generated by Django 4.2.30 on 2026-08-08 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usimamizi', '0016_parent_contact_call_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekodiMaendeleoMchana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarehe', models.DateField(auto_now_add=True, db_index=True)),
                ('mada_iliyosomwa', models.CharField(help_text='Mfano: Mlango wa Udhu', max_length=200)),
                ('ukurasa_au_aya', models.CharField(blank=True, max_length=50, null=True)),
                ('hali', models.CharField(choices=[('Ameelewa', '✅ Ameelewa'), ('Hajaelewa', '❌ Hajaelewa'), ('Hajasikilizwa', '⏸️ Hajasikilizwa')], max_length=20)),
                ('maoni', models.TextField(blank=True, null=True)),
                ('mwalimu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usimamizi.mwalimu')),
                ('mwanafunzi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maendeleo_mchana', to='usimamizi.mwanafunzi')),
                ('somo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maendeleo_mchana', to='usimamizi.somo')),
            ],
            options={
                'verbose_name': 'Rekodi ya maendeleo ya mchana',
                'verbose_name_plural': 'Rekodi za maendeleo ya mchana',
                'ordering': ['-tarehe', '-id'],
            },
        ),
    ]
