# Generated by Django 4.2.30 on 2026-08-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usimamizi', '0017_restore_maendeleo_mchana_ui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekodisimumzazi',
            name='matokeo',
            field=models.CharField(choices=[('alijibu', 'Alijibu'), ('hakujibu', 'Hakujibu'), ('imezimwa', 'Simu imezimwa'), ('siyo_sahihi', 'Namba si sahihi'), ('akaahidi', 'Akaahidi (malipo/kuja)'), ('imeanzishwa', 'Imeanzishwa (WhatsApp)'), ('nyingine', 'Nyingine')], db_index=True, default='alijibu', max_length=20),
        ),
        migrations.AlterField(
            model_name='rekodisimumzazi',
            name='sababu',
            field=models.CharField(choices=[('ada', 'Ada / malipo'), ('mahudhurio', 'Mahudhurio / utoro'), ('jumla', 'Habari za jumla'), ('whatsapp', 'WhatsApp'), ('nyingine', 'Nyingine')], db_index=True, default='ada', max_length=20),
        ),
    ]
