# Generated by Django 4.2.30 on 2026-08-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usimamizi', '0019_hamisha_darasa_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwanafunzi',
            name='jina_la_mzazi_pili',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jina la mzazi wa pili'),
        ),
        migrations.AddField(
            model_name='mwanafunzi',
            name='namba_ya_simu_mzazi_pili',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Namba ya simu (mzazi wa pili)'),
        ),
        migrations.AddField(
            model_name='mwanafunzi',
            name='uhusiano_wa_mlezi_pili',
            field=models.CharField(blank=True, choices=[('', '—'), ('Baba', 'Baba'), ('Mama', 'Mama'), ('Mlezi', 'Mlezi'), ('Mwingine', 'Mwingine')], default='', help_text='Uhusiano wa mzazi/mlezi wa pili (mf. Mama au Baba)', max_length=20, verbose_name='Uhusiano (mzazi wa pili)'),
        ),
        migrations.AlterField(
            model_name='mwanafunzi',
            name='jina_la_mzazi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jina la mzazi wa kwanza'),
        ),
        migrations.AlterField(
            model_name='mwanafunzi',
            name='namba_ya_simu_mzazi',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Namba ya simu (mzazi wa kwanza)'),
        ),
        migrations.AlterField(
            model_name='mwanafunzi',
            name='uhusiano_wa_mlezi',
            field=models.CharField(blank=True, choices=[('', '—'), ('Baba', 'Baba'), ('Mama', 'Mama'), ('Mlezi', 'Mlezi'), ('Mwingine', 'Mwingine')], default='', help_text='Uhusiano wa mzazi/mlezi wa kwanza (mf. Baba au Mama)', max_length=20, verbose_name='Uhusiano (mzazi wa kwanza)'),
        ),
    ]
