# Generated by Django 4.2.30 on 2026-08-08 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usimamizi', '0020_mzazi_wa_pili'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ainamalipo',
            options={'ordering': ['-mwaka__mwaka_kuanzia', 'mwezi', 'jina'], 'verbose_name_plural': 'Aina za malipo'},
        ),
        migrations.AddField(
            model_name='ainamalipo',
            name='mwaka',
            field=models.ForeignKey(blank=True, help_text='Mwaka wa masomo unaohusiana na ada hii', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aina_za_malipo', to='usimamizi.mwakawamasomo'),
        ),
        migrations.AddField(
            model_name='ainamalipo',
            name='mwezi',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Machi'), (4, 'Aprili'), (5, 'Mei'), (6, 'Juni'), (7, 'Julai'), (8, 'Agosti'), (9, 'Septemba'), (10, 'Oktoba'), (11, 'Novemba'), (12, 'Desemba')], help_text='Kwa ada ya mwezi — chagua mwezi (pamoja na mwaka)', null=True),
        ),
        migrations.AlterField(
            model_name='ainamalipo',
            name='jina',
            field=models.CharField(help_text='Mfano: Ada ya mwezi, Mchango wa mtihani', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='ainamalipo',
            constraint=models.UniqueConstraint(condition=models.Q(('mwaka__isnull', False), ('mwezi__isnull', False)), fields=('mwaka', 'mwezi'), name='unique_ada_mwezi_per_mwaka'),
        ),
        migrations.AddConstraint(
            model_name='ainamalipo',
            constraint=models.UniqueConstraint(condition=models.Q(('mwaka__isnull', False)), fields=('mwaka', 'jina'), name='unique_ada_jina_per_mwaka'),
        ),
    ]
